---
title: "Analysis_Exp1"
output: html_document
date: "2023-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(qdapTools)


rm(list=ls()) #Clear environment

load("Exp1.RData")
```

```{r}
#Summary of raw data

temp1 <- aggregate(data1$F1_Change,
                   list(data1$Direction, data1$Block),
                   FUN = mean)

colnames(temp1) <- c("Direction", "Block", "Value")

#Summary of fitted value

temp2 <- aggregate(data1b$fit,
                   list(data1b$Direction, data1b$Block),
                   FUN = mean)

colnames(temp2) <- c("Direction", "Block", "Fitted")

#Summary of CI

temp3 <- aggregate(data1b$CI,
                   list(data1b$Direction, data1b$Block),
                   FUN = mean)

colnames(temp3) <- c("Direction", "Block", "CI")

#Combine CI with the fitted values

temp2$Tracer <- paste(temp2$Block, temp2$Direction, sep = "_")

temp3$Tracer <- paste(temp3$Block, temp3$Direction, sep = "_")

temp2$CI <- lookup(terms = temp2$Tracer,
                   key.match = temp3$Tracer,
                   key.reassign = temp3$CI)
```

```{r}
ggplot() +
  geom_hline(yintercept = 0, color = "black", linewidth = 0.3) + 
  geom_point(data = temp1, 
             aes(x = Block, y = Value, color = Direction),
             alpha = 0.3) +
  geom_line(data = temp2, 
            aes(x = Block, y = Fitted, color = Direction),
            linewidth = 1) + 
  geom_ribbon(data = temp2, aes(x = Block, 
                                ymin = Fitted + CI, 
                                ymax = Fitted - CI, 
                                fill = Direction),
              alpha = 0.2) + 
  theme_classic() +
  ylab("F1 change (mel)") +
  xlab("Block") +
  scale_color_manual(values = c("blue", "gray", "red")) +
  scale_fill_manual(values = c("blue", "gray", "red")) +
  theme(legend.background = element_blank(),
        legend.title = element_blank(),
        legend.position = c(0.1, 0.85), ) +
  scale_x_continuous(limits = c(1, max(data1$Block)), expand = c(0, 0)) +
  ggtitle("Experiment 1")
```


