
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(qdapTools)

library(sp)
library(beepr)

library(mgcv)
library(itsadug)

rm(list=ls()) #Clear environment

load("Exp2.RData")
```

#Prep
```{r}
data2$Direction <- factor(data2$Direction)

contrasts(data2$Direction) = contr.sum(3)

contrasts(data2$Direction)

data2$Speaker <- factor(data2$Speaker)

#Add Start info

data2$Initial <- ifelse(data2$Block == 1, TRUE, FALSE)

table(data2$Block, data2$Direction)
```

#Model
```{r}
#Adding nonlinear pattern over Blocks

m2a <- bam(F1_Change ~ Direction +  
              s(Block, bs = "tp", k = 20),  
            data = data2, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m2a)

m2a_AR <- bam(formula(m2a), 
            rho = var_AR[2], AR.start = data2$Initial,
            data = data2, method = "ML")

summary(m2a_AR) 
gam.check(m2a_AR)

#beep(sound = 0)
```

```{r}
#Adding nonlinear pattern over Blocks for each Direction

m2b <- bam(F1_Change ~ Direction +  
              s(Block, bs = "tp", by = Direction, k = 20), 
            data = data2, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m2b)

m2b_AR <- bam(formula(m2b), 
            rho = var_AR[2], AR.start = data2$Initial,
            data = data2, method = "ML")

#Model comparison

compareML(m2a_AR, m2b_AR) #model m2b_AR has lower AIC.

#beep(sound = 0)
```

```{r}
#Add random intercept by speaker
m2c <- bam(F1_Change ~ Direction +  
             s(Block, by = Direction, k = 20) + 
             s(Speaker, bs = "re"),
           data = data2, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m2c)

m2c_AR <- bam(formula(m2c), 
            rho = var_AR[2], AR.start = data2$Initial,
            data = data2, method = "ML")

compareML(m2b_AR, m2c_AR) #model m2c_AR has lower AIC.

#beep(sound = 0)
```

```{r}
#Add random intercept by Speaker per Direction (as a random slope)
m2d <- bam(F1_Change ~ Direction +  
             s(Block, by = Direction, k = 20) + 
             s(Speaker, Direction, bs = "re"),
           data = data2, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m2d)

m2d_AR <- bam(formula(m2d), 
            rho = var_AR[2], AR.start = data2$Initial,
            data = data2, method = "ML")

compareML(m2c_AR, m2d_AR) #Model m2d_AR preferred

#beep(sound = 0)
```

```{r}
#Try adding by speaker smooth
m2e <- bam(F1_Change ~ Direction +  
             s(Block, by = Direction, k = 20) + 
             s(Speaker, Direction, bs = "re") +
             s(Block, Speaker,bs = "fs",m = 1),
           data = data2, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m2e)

m2e_AR <- bam(formula(m2e), 
            rho = var_AR[2], AR.start = data2$Initial,
            data = data2, method = "ML")

compareML(m2d_AR, m2e_AR) #model m2e_AR has lower AIC.

#beep(sound = 0)
```

#Visualize results 

```{r}
two.colors = c("blue", "gray", "red")

plot_smooth(m2e_AR, view = "Block", 
            plot_all = c("Direction"),
            #se = 0, lwd = 2,
            legend_plot_all = "topleft",
            xlab = "Block",
            ylab = "F1 change (mel)", 
            main = "Fitted values", 
            rug = FALSE, col = two.colors)

plot_diff(m2e_AR, view = "Block",
          xlab = "Block",
          ylab = "F1 change (mel)", 
          main = "Downshift - Upshift", 
          comp = list(Direction = c("Downshift", "Upshift")))
```

#Obtain fitted values

```{r}
data2b <- get_fitted(m2e_AR, 
                    se = 1, 
                    as.data.frame = TRUE)

save.image("Exp2.RData")
```

