
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(qdapTools)

library(sp)
library(beepr)

library(mgcv)
library(itsadug)

rm(list=ls()) #Clear environment

load("Exp3.RData")
```

#Prep
```{r}
data3$Direction <- factor(data3$Direction)

contrasts(data3$Direction) = contr.sum(3)

contrasts(data3$Direction)

data3$Speaker <- factor(data3$Speaker)

#Add Start info

data3$Initial <- ifelse(data3$Block == 1, TRUE, FALSE)

table(data3$Block, data3$Direction)
```

#Model
```{r}
#Adding nonlinear pattern over Blocks

m3a <- bam(F1_Change ~ Direction +  
              s(Block, bs = "tp", k = 20),  
            data = data3, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m3a)

m3a_AR <- bam(formula(m3a), 
            rho = var_AR[2], AR.start = data3$Initial,
            data = data3, method = "ML")

summary(m3a_AR) 
gam.check(m3a_AR)

#beep(sound = 0)
```

```{r}
#Adding nonlinear pattern over Blocks for each Direction

m3b <- bam(F1_Change ~ Direction +  
              s(Block, bs = "tp", by = Direction, k = 20), 
            data = data3, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m3b)

m3b_AR <- bam(formula(m3b), 
            rho = var_AR[2], AR.start = data3$Initial,
            data = data3, method = "ML")

#Model comparison

compareML(m3a_AR, m3b_AR) #model m3b_AR has lower AIC.

#beep(sound = 0)
```

```{r}
#Add random intercept by speaker
m3c <- bam(F1_Change ~ Direction +  
             s(Block, by = Direction, k = 20) + 
             s(Speaker, bs = "re"),
           data = data3, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m3c)

m3c_AR <- bam(formula(m3c), 
            rho = var_AR[2], AR.start = data3$Initial,
            data = data3, method = "ML")

compareML(m3b_AR, m3c_AR) #model m3c_AR has lower AIC.

#beep(sound = 0)
```

```{r}
#Add random intercept by Speaker per Direction (as a random slope)
m3d <- bam(F1_Change ~ Direction +  
             s(Block, by = Direction, k = 20) + 
             s(Speaker, Direction, bs = "re"),
           data = data3, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m3d)

m3d_AR <- bam(formula(m3d), 
            rho = var_AR[2], AR.start = data3$Initial,
            data = data3, method = "ML")

compareML(m3c_AR, m3d_AR) #Model m3d_AR preferred

#beep(sound = 0)
```

```{r}
#Try adding by speaker smooth
m3e <- bam(F1_Change ~ Direction +  
             s(Block, by = Direction, k = 20) + 
             s(Speaker, Direction, bs = "re") +
             s(Block, Speaker,bs = "fs",m = 1),
           data = data3, method = "ML")

#Remove autocorrelation

var_AR <- acf_resid(m3e)

m3e_AR <- bam(formula(m3e), 
            rho = var_AR[2], AR.start = data3$Initial,
            data = data3, method = "ML")

compareML(m3d_AR, m3e_AR) #model m3e_AR has lower AIC.

#beep(sound = 0)
```

#Visualize results 

```{r}
two.colors = c("blue", "gray", "red")

plot_smooth(m3e_AR, view = "Block", 
            plot_all = c("Direction"),
            #se = 0, lwd = 2,
            legend_plot_all = "topleft",
            xlab = "Block",
            ylab = "F1 change (mel)", 
            main = "Fitted values", 
            rug = FALSE, col = two.colors)

plot_diff(m3e_AR, view = "Block",
          xlab = "Block",
          ylab = "F1 change (mel)", 
          main = "Downshift - Upshift", 
          comp = list(Direction = c("Downshift", "Upshift")))
```

#Obtain fitted values

```{r}
data3b <- get_fitted(m3e_AR, 
                    se = 1, 
                    as.data.frame = TRUE)

save.image("Exp3.RData")
```

