---
title: "Analysis_Exp123_Dur"
output: html_document
date: "2023-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(ggpubr)

library(qdapTools)
library(Rmisc)

library(lme4)
library(lmerTest)
library(buildmer)

library(phia)

library(MuMIn)
library(r2glmm)
library(effsize)
library(dlookr)
```

#Combine data

```{r}
data12$Exp <- "Experiment 1"
data22$Exp <- "Experiment 2"
data32$Exp <- "Experiment 3"

#Set up columns to include

temp1 <- c("Exp", "Speaker", "Trial", "Block_10",
           "Word", "Phase", "Direction", 
           "Duration")

data51 <- rbind(data12[, temp1], data22[, temp1], data32[, temp1])

```

```{r}
#Plot as sanity check
temp1 <- aggregate(data51$Duration, 
                   list(data51$Exp,
                        data51$Direction, data51$Phase), 
                   FUN = mean) 

colnames(temp1) <- c("Exp", "Direction", "Phase", "Duration")

temp2 <- aggregate(data51$Duration, 
                   list(data51$Exp,
                        data51$Direction, data51$Phase), 
                   FUN = standard_error) 


temp1$se <- temp2$x

ggplot(data = temp1, aes(x = Exp, y = Duration)) + 
  theme_classic() + 
  ylab("Duration (ms)") + 
  geom_point() + 
  geom_errorbar(aes(ymin = Duration - se, ymax = Duration + se), 
                width = 0.5,
                position = position_dodge(0)) + 
  theme(legend.position = "none", 
        legend.title = element_blank(), 
        legend.text = element_text(size = 10, margin = margin(r = 30)),
        axis.title.x = element_blank(),
        plot.title = element_blank(),
        strip.text = element_text(size = 20),
        axis.title.y = element_text(size = 18),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14)) + 
  facet_grid(Direction ~ Phase)
```

#Model duration differences across experiments 
```{r}
data51$Phase <- factor(data51$Phase)

contrasts(data51$Phase) = contr.sum(2)

contrasts(data51$Phase)

data51$Exp <- factor(data51$Exp)

contrasts(data51$Exp) = contr.sum(3)

contrasts(data51$Exp)

data51$Direction <- factor(data51$Direction)

contrasts(data51$Direction) = contr.sum(2)

contrasts(data51$Direction)

f <- Duration ~ Direction * Phase * Exp +
  (Direction * Phase * Exp | Speaker) + 
  (Direction * Phase * Exp| Word)

m.order <- buildmer(f,
                    data = data51,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = data51,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
m5 <- lmer(f,
           data = data51,
           control = lmerControl(optimizer = "bobyqa",
                                 optCtrl = list(maxfun = 2e5)),
           REML = TRUE)

car::Anova(m5, type = 3)

#Post-hoc

testInteractions(m5, 
                 fixed = c(), 
                 pairwise = c("Exp"))

testInteractions(m5, 
                 fixed = c("Phase"), 
                 pairwise = c("Exp"))

testInteractions(m5, 
                 fixed = c("Exp"), 
                 pairwise = c())

testInteractions(m5, 
                 fixed = c("Exp"), 
                 pairwise = c("Phase"))

```

```{r}
aggregate(data51$Duration, 
          list(data51$Exp), 
          FUN = mean)

aggregate(data51$Duration, 
          list(data51$Exp), 
          FUN = standard_error) 

aggregate(data51$Duration, 
          list(data51$Exp, data51$Phase), 
          FUN = mean)

aggregate(data51$Duration, 
          list(data51$Exp, data51$Phase), 
          FUN = standard_error)
```

```{r}
r2beta(m5, partial = TRUE, 
       method = "nsj")

```

```{r}
#Cohen's d

temp1 <- data51[which(data51$Exp == "Experiment 1"), "Duration"]
temp2 <- data51[which(data51$Exp == "Experiment 2"), "Duration"]
temp3 <- data51[which(data51$Exp == "Experiment 3"), "Duration"]

cohen.d(temp1, temp2)
cohen.d(temp1, temp3)
cohen.d(temp2, temp3)

#Interaction

temp1 <- data51[which(data51$Exp == "Experiment 1" & data51$Phase == "Hold"),
                "Duration"]
temp2 <- data51[which(data51$Exp == "Experiment 1" & data51$Phase == "Washout"),
                "Duration"]

cohen.d(temp1, temp2)

#Interaction

temp1 <- data51[which(data51$Exp == "Experiment 2" & data51$Phase == "Hold"),
                "Duration"]
temp2 <- data51[which(data51$Exp == "Experiment 2" & data51$Phase == "Washout"),
                "Duration"]

cohen.d(temp1, temp2)

#Interaction

temp1 <- data51[which(data51$Exp == "Experiment 3" & data51$Phase == "Hold"),
                "Duration"]
temp2 <- data51[which(data51$Exp == "Experiment 3" & data51$Phase == "Washout"),
                "Duration"]

cohen.d(temp1, temp2)

#Interaction

temp1 <- data51[which(data51$Exp == "Experiment 1" & data51$Phase == "Hold"),
                "Duration"]
temp2 <- data51[which(data51$Exp == "Experiment 2" & data51$Phase == "Hold"),
                "Duration"]
temp3 <- data51[which(data51$Exp == "Experiment 3" & data51$Phase == "Hold"),
                "Duration"]

cohen.d(temp1, temp2)
cohen.d(temp1, temp3)
cohen.d(temp2, temp3)

temp1 <- data51[which(data51$Exp == "Experiment 1" & data51$Phase == "Washout"),
                "Duration"]
temp2 <- data51[which(data51$Exp == "Experiment 2" & data51$Phase == "Washout"),
                "Duration"]
temp3 <- data51[which(data51$Exp == "Experiment 3" & data51$Phase == "Washout"),
                "Duration"]

cohen.d(temp1, temp2)
cohen.d(temp1, temp3)
cohen.d(temp2, temp3)
```

#Adding duration to the original adaptation size model
```{r}
#Data prep

temp1 <- aggregate(data51$Duration, 
                   list(data51$Exp,
                        data51$Direction, data51$Phase, data51$Speaker), 
                   FUN = mean)

colnames(temp1) <- c("Exp", "Direction", "Phase", "Speaker", "Duration")

temp1 <- spread(temp1, key = Direction, value = Duration)

temp1$DownUp <- (temp1$Downshift + temp1$Upshift)/2 #Calculate

#Set aside a data frame

data52 <- temp1

#Pair with data41

data41$Tracer <- paste(data41$EXP, data41$Speaker, data41$Phase, sep = "_")
data52$Tracer <- paste(data52$Exp, data52$Speaker, data52$Phase, sep = "_")

data41$Duration <- lookup(terms = data41$Tracer,
                          key.match = data52$Tracer,
                          key.reassign = data52$DownUp)

head(data41)
```

```{r}
#Model update

m41 <- lmer(DownUp ~ Exp + Phase + Exp:Phase + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m41)
```

```{r}
m42 <- lmer(DownUp ~ Exp:Duration + Phase + Exp:Phase + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m42)
```

```{r}
m43 <- lmer(DownUp ~ Exp + Phase:Duration + Exp:Phase + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m43)
```

```{r}
m44 <- lmer(DownUp ~ Exp + Phase + Exp:Phase:Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m44)
```

```{r}
m45 <- lmer(DownUp ~ Exp:Duration + Phase:Duration + Exp:Phase + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m45)
```

```{r}
m46 <- lmer(DownUp ~ Exp:Duration + Phase + Exp:Phase:Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m46)
```

```{r}
m47 <- lmer(DownUp ~ Exp + Phase:Duration + Exp:Phase:Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m47)
```

```{r}
m48 <- lmer(DownUp ~ Exp:Duration + Phase + Exp:Phase + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m48)
```

```{r}
m49 <- lmer(DownUp ~ Exp + Phase:Duration + Exp:Phase + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m49)
```

```{r}
m410 <- lmer(DownUp ~ Exp + Phase + Exp:Phase:Duration + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m410)
```

```{r}
m411 <- lmer(DownUp ~ Exp:Duration + Phase:Duration + Exp:Phase:Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m411)
```

```{r}
m412 <- lmer(DownUp ~ Exp:Duration + Phase:Duration + Exp:Phase + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m412)
```

```{r}
m413 <- lmer(DownUp ~ Exp:Duration + Phase + Exp:Phase:Duration + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m413)
```

```{r}
m414 <- lmer(DownUp ~ Exp + Phase:Duration + Exp:Phase:Duration + Duration + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m414)
```

```{r}
m415 <- lmer(DownUp ~ Exp:Duration + Phase: Duration + Exp:Phase:Duration + Duration  + (1 | Speaker),
            data = data41,
            control = lmerControl(optimizer = "bobyqa",
                                  optCtrl = list(maxfun = 2e5)),
            REML = TRUE)

anova(m4, m415)
```

#Re-run model selection

```{r}
f <- DownUp ~ Phase * EXP * Duration + 
  (Phase * EXP * Duration | Speaker)

m.order <- buildmer(f,
                    data = data41,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = data41,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
m4.a <- lmer(f,
             data = data41,
             control = lmerControl(optimizer = "bobyqa",
                                   optCtrl = list(maxfun = 2e5)),
             REML = TRUE)

summary(m4.a)

car::Anova(m4.a, type = 3)

anova(m4, m4.a)

#Post-hoc

testInteractions(m4.a, 
                 fixed = c(), 
                 pairwise = c("EXP"))

testInteractions(m4.a, 
                 fixed = c("Phase"), 
                 pairwise = c("EXP"))

testInteractions(m4.a, 
                 fixed = c("EXP"), 
                 pairwise = c("Phase"))

```

```{r}
r2beta(m4.a, partial = TRUE, 
       method = "nsj")

```


