---
title: "Analysis_Exp2"
output: html_document
date: "2023-10-12"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(qdapTools)
library(Rmisc)

```

#Group 1
```{r}
head(data2)

temp1 <- data.frame(c(1:max(data2$Trial)))
var1 <- max(data2$Trial) / length(unique(data2$Word))

temp2 <- data.frame(rep(c(1:var1), each = length(unique(data2$Word)), length.out = max(data2$Trial)))

temp1 <- cbind(temp1, temp2)

colnames(temp1) <- c("Trial", "Group1")

data2$Group1 <- lookup(terms = data2$Trial,
                       key.match = temp1$Trial,
                       key.reassign = temp1$Group1)
```


```{r}
#Plot

data2$Direction <- factor(data2$Direction, levels = c("Upshift", 
                                                      "Downshift", 
                                                      "Unshifted"))

temp2 <- summarySEwithin(data = data2, 
                         measurevar = "F1_Change",
                         withinvars = c("Direction", "Group1"), 
                         idvar = "Speaker",
                         na.rm = TRUE)

temp2$Group1 <- as.numeric(as.character(temp2$Group1))
range(temp2$Group1)

ggplot(data = temp2, aes(x = Group1, y = F1_Change, color = Direction)) +
  geom_point() + 
  theme_classic() + 
  ylab("F1 change (mel)") + 
  #geom_vline(xintercept = bar_1, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #geom_vline(xintercept = bar_2, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #geom_vline(xintercept = bar_3, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #annotate("rect", xmin = 155, xmax = 165, ymin = -55, ymax = 55,
  #         alpha = 0.2,fill = "yellow") + 
  #annotate("rect", xmin = 125, xmax = 135, ymin = -55, ymax = 55,
  #         alpha = 0.2,fill = "yellow") + 
  #annotate(geom = "text", x = var_Baseline, y = 50, 
  #         label = "Baseline",color = "black", size = rel(3.0)) +  
  #annotate(geom = "text", x = var_Ramp, y = 50, 
  #         label = "Ramp", color = "black", size = rel(3.0)) + 
  #annotate(geom = "text", x = var_Hold, y =  50, 
  #         label = "Hold", color = "black", size = rel(3.0)) + 
  #annotate(geom = "text", x = var_Washout, y =  50, 
  #         label = "Washout", color = "black", size = rel(3.0)) +
  geom_hline(yintercept = 0, linetype = "solid", 
             color = "black", linewidth = 0.8) + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        axis.text = element_text(size = rel(1.0)), 
        axis.title.y = element_text(size = rel(1.0)), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) + 
  scale_x_continuous(expand = c(0, 0), limits = c(1, 135)) +
  #scale_y_continuous(expand = c(0, 0), limits = c(-55, 55)) +
  scale_color_manual(values = c("red", "blue", "gray")) +
  ggtitle("Expriment 2_Group1")

ggsave(filename = "Exp2_Group1.png",
       dpi = 600,
       units = "in",
       width = 7.5,
       height = 3)
```

#Group2

```{r}
temp2 <- data.frame(rep(c(1:var1), each = length(unique(data2$Word)) * 2, length.out = max(data2$Trial)))

temp1 <- cbind(temp1, temp2)

colnames(temp1) <- c("Trial", "Group1", "Group2")

data2$Group2 <- lookup(terms = data2$Trial,
                       key.match = temp1$Trial,
                       key.reassign = temp1$Group2)
```

```{r}
#Plot

temp2 <- summarySEwithin(data = data2, 
                         measurevar = "F1_Change",
                         withinvars = c("Direction", "Group2"), 
                         idvar = "Speaker",
                         na.rm = TRUE)

temp2$Group2 <- as.numeric(as.character(temp2$Group2))
range(temp2$Group2)

ggplot(data = temp2, aes(x = Group2, y = F1_Change, color = Direction)) +
  geom_point() + 
  theme_classic() + 
  ylab("F1 change (mel)") + 
  #geom_vline(xintercept = bar_1, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #geom_vline(xintercept = bar_2, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #geom_vline(xintercept = bar_3, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #annotate("rect", xmin = 155, xmax = 165, ymin = -55, ymax = 55,
  #         alpha = 0.2,fill = "yellow") + 
  #annotate("rect", xmin = 125, xmax = 135, ymin = -55, ymax = 55,
  #         alpha = 0.2,fill = "yellow") + 
  #annotate(geom = "text", x = var_Baseline, y = 50, 
  #         label = "Baseline",color = "black", size = rel(3.0)) +  
  #annotate(geom = "text", x = var_Ramp, y = 50, 
  #         label = "Ramp", color = "black", size = rel(3.0)) + 
  #annotate(geom = "text", x = var_Hold, y =  50, 
  #         label = "Hold", color = "black", size = rel(3.0)) + 
  #annotate(geom = "text", x = var_Washout, y =  50, 
  #         label = "Washout", color = "black", size = rel(3.0)) +
  geom_hline(yintercept = 0, linetype = "solid", 
             color = "black", linewidth = 0.8) + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        axis.text = element_text(size = rel(1.0)), 
        axis.title.y = element_text(size = rel(1.0)), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) + 
  #scale_x_continuous(expand = c(0, 0), limits = c(1, 135)) +
  #scale_y_continuous(expand = c(0, 0), limits = c(-55, 55)) +
  scale_color_manual(values = c("red", "blue", "gray")) +
  ggtitle("Expriment 2_Group2")

ggsave(filename = "Exp2_Group2.png",
       dpi = 600,
       units = "in",
       width = 7.5,
       height = 3)
```


