---
title: "Analysis_Exp3"
output: html_document
date: "2023-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(ggpubr)

library(qdapTools)
library(Rmisc)

library(lme4)
library(lmerTest)
library(buildmer)

library(phia)

library(MuMIn)
library(r2glmm)

library(effsize)
```

#Normalization

```{r}
data3 <- read.csv("F1_Exp3.csv")

data3 <- unique(data3)

#Add Block_10 info

data3$Block_10 <- ceiling(data3$Trial/40)

data3 <- data3[which(data3$Word != "carbonate"), ]

temp1 <- data.frame(table(data3$Speaker, data3$Block_10, data3$Phase))

#Obtain baseline means

temp1 <- aggregate(data3$meanF1_mel, 
                   list(data3$Direction, data3$Block_10, data3$Speaker), 
                   FUN = mean) 

colnames(temp1) <- c("Direction", "Block_10", "Speaker", "meanF1")

#Limit results to the last 10 trials of baseline 

##Where is it?

temp2 <- data.frame(table(data3$Block_10, data3$Phase))
temp2 <- temp2[which(temp2$Freq != 0 & temp2$Var2 == "Baseline"),]
var1 <- max(as.numeric(as.character(temp2$Var1)))

#Found it
temp1 <- temp1[which(temp1$Block_10 == var1), ]

temp1$Tracer <- paste(temp1$Speaker, temp1$Direction, sep = "_")

data3$Tracer <- paste(data3$Speaker, data3$Direction, sep = "_")

#Pairing data from temp1 

data3$F1_Baseline <- lookup(terms = data3$Tracer, 
                            key.match = temp1$Tracer,
                            key.reassign = temp1$meanF1)

#Calculate F1 change 

data3$F1_Change <- data3$meanF1_mel - data3$F1_Baseline

#Add frequency

data3$Lexical <- ifelse(data3$Word == "pedicure", log10(0.00001/100), 
                        ifelse(data3$Word == "pedestal", log(0.0002/100), log(0.0001/100)))

table(data3$Lexical, data3$Word)
```

#P1, result figure

```{r}
#Set up bars and labels

bar_1 = 25
bar_2 = 55
bar_3 = 125

var_Baseline = bar_1 / 2
var_Ramp = (bar_1 + bar_2) /2 
var_Hold = (bar_2 + bar_3) /2 
var_Washout = bar_3 + 11
```

```{r}
#Plot grand average

data3$Direction <- factor(data3$Direction, levels = c("Upshift", 
                                                      "Downshift", 
                                                      "Unshifted"))


temp1 <- summarySEwithin(data = data3, 
                         measurevar = "F1_Change",
                         withinvars = c("Direction", "Block_10"), 
                         idvar = "Speaker",
                         na.rm = TRUE)

temp1$Block_10 <- as.numeric(temp1$Block_10) * 10

ggplot(data = temp1, aes(x = Block_10, y = F1_Change, 
                               color = Direction)) +
  geom_point() + 
  geom_line() + 
  geom_errorbar(aes(ymin = F1_Change - se, ymax = F1_Change + se), 
                width = 4,
                position = position_dodge(0)) + 
  theme_classic() + 
  ylab("F1 change (mel)") + 
  geom_hline(yintercept = 0, linetype = "solid", 
             color = "black", linewidth = 0.5) + 
  geom_vline(xintercept = bar_1, linetype = "twodash", 
             color = "black", linewidth = 0.7) + 
  geom_vline(xintercept = bar_2, linetype = "twodash", 
             color = "black", linewidth = 0.7) + 
  geom_vline(xintercept = bar_3, linetype = "twodash", 
             color = "black", linewidth = 0.7) + 
  annotate("rect", xmin = 115, xmax = 135, ymin = -10, ymax = 25,
           alpha = 0.2,fill = "yellow") +
  annotate(geom = "text", x = var_Baseline, y = max(temp1$F1_Change), 
           label = "Baseline",color = "black", size = 5) +  
  annotate(geom = "text", x = var_Ramp, y = max(temp1$F1_Change), 
           label = "Ramp", color = "black", size = 5) + 
  annotate(geom = "text", x = var_Hold, y =  max(temp1$F1_Change), 
           label = "Hold", color = "black", size = 5) + 
  annotate(geom = "text", x = var_Washout, y =  max(temp1$F1_Change), 
           label = "Washout", color = "black", size = 5) +
  theme(legend.position = "none", 
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) + 
  scale_x_continuous(expand = c(0, 0), limits = c(1, 145), 
                     breaks = c(10, 20, 30, 50, 60, 
                                120, 130)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-10, 25), 
                     breaks = seq(-40, 50, by = 10)) +
  scale_color_manual(values = c("red", "blue", "gray")) 

ggsave(filename = "3B.png",
       plot = last_plot(), 
       dpi = 600,
       width = 9,
       height = 4)
```

#P2, perturbations 

```{r}
#Numbers
Block_10s <- c(1, 24.99, 54.999, 110, 124.999, 125, 135)

Shifts <- c("Unshifted", "Upshift", "Downshift")

temp1 <- expand.grid(Block_10s, Shifts)

colnames(temp1) <- c("Block_10", "Direction")

temp1$Mags <- c(0, 0, 0, 0, 0, 0, 0, 
                2.0, 2.0, 125, 125, 125, 2.0, 2.0,
                -2.0, -2.0, -125, -125, -125, -2.0, -2.0)

temp1$Direction <- factor(temp1$Direction, levels = c("Upshift", 
                                                      "Downshift",
                                                      "Unshifted"))
```

```{r}
#Plot

ggplot(data = temp1, 
             aes(x = Block_10, y = Mags, color = Direction)) +
  geom_line(linewidth = 1) + 
  theme_classic() + 
  ylab("F1 pert (mel)") + 
  theme(legend.position = "none", 
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + 
  scale_y_continuous(expand = c(0, 0), limits = c(-130, 130), 
                     breaks = c(-125, 0, 125)) +
  scale_x_continuous(expand = c(0, 0), limits = c(1, 145), 
                     breaks = c(10, 20, 30, 50, 60, 
                                120, 130)) +
  scale_color_manual(values = c("red", "blue", "gray"))

ggsave(filename = "3A.png",
       plot = last_plot(), 
       dpi = 600,
       width = 9,
       height = 1.5)
```

#Calculate Downshift - Upshift

```{r}
#Calculate Downshift & Upshift for individual speakers 

temp2 <- aggregate(data3$F1_Change, 
                   list(data3$Direction, data3$Block_10, data3$Speaker), 
                   FUN = mean) 

colnames(temp2) <- c("Direction", "Block_10", "Speaker", "meanF1")

temp2 <- temp2[which(temp2$Direction != "Unshifted"), ]

temp3 <- spread(data = temp2, key = Direction, value = meanF1)

temp3$DownUp <- temp3$Downshift - temp3$Upshift

#Summary

temp2 <- summarySEwithin(data = temp3, 
                         measurevar = "DownUp",
                         withinvars = c("Block_10"), 
                         idvar = "Speaker",
                         na.rm = TRUE)

temp2$Block_10 <- as.numeric(temp2$Block_10) * 10

```

```{r}
#Plot

ggplot(data = temp2, aes(x = Block_10, y = DownUp)) +
  geom_point() + 
  geom_line() + 
  geom_errorbar(aes(ymin = DownUp - se, ymax = DownUp + se), 
                width = 4,
                position = position_dodge(0)) + 
  theme_classic() + 
  geom_hline(yintercept = 0, linetype = "solid", 
             color = "black", linewidth = 0.5) + 
  theme() + 
  annotate("rect", xmin = 115, xmax = 135, ymin = -5, ymax = 23,
           alpha = 0.2,fill = "yellow") +
  geom_hline(yintercept = 0, linetype = "solid", 
             color = "black", linewidth = 0.5) + 
  geom_vline(xintercept = bar_1, linetype = "twodash", 
             color = "black", linewidth = 0.7) + 
  geom_vline(xintercept = bar_2, linetype = "twodash", 
             color = "black", linewidth = 0.7) + 
  geom_vline(xintercept = bar_3 - 0.5, linetype = "twodash", 
             color = "black", linewidth = 0.7) + 
  scale_x_continuous(expand = c(0, 0), limits = c(1, 145), 
                     breaks = c(10, 20, 30, 50, 60, 
                                120, 130)) +
  scale_y_continuous(expand = c(0, 0), limits = c(-5, 23), 
                     breaks = c(0, 20),
                     labels = c("0", "20")) +
  ylab("Down - Up (mel)") + 
  xlab("Blocks")

ggsave(filename = "3C.png",
       plot = last_plot(), 
       dpi = 600,
       width = 9,
       height = 2)
```

#Plot individual participant data

```{r}
temp1 <- summarySEwithin(data = data3, 
                         measurevar = "F1_Change",
                         withinvars = c("Direction", "Block_10", "Speaker"), 
                         na.rm = TRUE)

#Restricted to last 10 trials of Hold and Washout

temp2 <- temp1[which(temp1$Block_10 %in% c(12, 13)), ]
temp2 <- temp2[which(temp2$Direction != "Unshifted"), ]

temp2$Block_10 <- ifelse(temp2$Block_10 == 12, "Hold", "Washout")

temp2$Direction <- factor(temp2$Direction, levels = c("Downshift", "Upshift"))


ggplot(data = temp2, aes(x = Direction, y = F1_Change, 
                               group = Speaker, color = Speaker)) +
  geom_line() + 
  geom_point() + 
  theme_classic() + 
  geom_hline(yintercept = 0, linetype = "dashed", 
             color = "black", linewidth = 0.5) + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        #axis.text = element_blank(),
        strip.text.x = element_text(size = 15)) +
  ylab("F1 change (mel)") +
  facet_grid(~ Block_10) + 
  scale_y_continuous(expand = c(0, 0), limits = c(-50, 70), 
                     breaks = c(-40, -20, 0, 20, 40, 60))

ggsave(filename = "3D.png",
       plot = last_plot(), 
       dpi = 600,
       width = 9,
       height = 4)


```

#Model fit

```{r}
#Restrict to the shaded trials

head(data3)

data31 <- data3[which(data3$Block_10 %in% c(12, 13)), ]

data31$Phase <- factor(data31$Phase)

contrasts(data31$Phase) = contr.sum(2)

contrasts(data31$Phase)

data31$Direction <- factor(data31$Direction)

contrasts(data31$Direction) = contr.sum(3)

contrasts(data31$Direction)

f <- F1_Change ~ Direction * Phase + 
  (Direction * Phase | Speaker) + (Direction * Phase | Word)

m.order <- buildmer(f,
                    data = data31,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = data31,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
m3 <- lmer(f,
           data = data31,
           control = lmerControl(optimizer = "bobyqa",
                                 optCtrl = list(maxfun = 2e5)),
           REML = TRUE)

car::Anova(m3, type = 3)

#Post-hoc

testInteractions(m3, 
                 pairwise = c("Direction"))

testInteractions(m3, 
                 fixed = c("Direction"))

testInteractions(m3, 
                 fixed = c("Phase"), 
                 pairwise = c("Direction"))

testInteractions(m3, 
                 fixed = c("Direction"), 
                 pairwise = c("Phase"))

testInteractions(m3, 
                 fixed = c("Phase", "Direction"))
```

#Frequency & Lexical 


```{r}
#Restrict to the shaded trials

head(data3)

data31 <- data3[which(data3$Block_10 %in% c(12, 13)), ]

data31$Phase <- factor(data31$Phase)

contrasts(data31$Phase) = contr.sum(2)

contrasts(data31$Phase)

data31$Direction <- factor(data31$Direction)

contrasts(data31$Direction) = contr.sum(3)

contrasts(data31$Direction)

f <- F1_Change ~ Direction * Phase * Duration * Lexical + 
  (Direction * Phase | Speaker) + (Direction * Phase | Word)

m.order <- buildmer(f,
                    data = data31,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = data31,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
m3 <- lmer(f,
           data = data31,
           control = lmerControl(optimizer = "bobyqa",
                                 optCtrl = list(maxfun = 2e5)),
           REML = TRUE)

#Rank deficiency

m3 <- lmer(F1_Change ~ Direction + Phase + Direction:Phase + Duration + 
    Direction:Duration + Lexical + (1 + Direction + Phase | Speaker),
           data = data31,
           control = lmerControl(optimizer = "bobyqa",
                                 optCtrl = list(maxfun = 2e5)),
           REML = TRUE)

car::Anova(m3, type = 3)

#Post-hoc

testInteractions(m3, 
                 pairwise = c("Direction"))

testInteractions(m3, 
                 fixed = c("Direction"))

testInteractions(m3, 
                 fixed = c("Phase"), 
                 pairwise = c("Direction"))

testInteractions(m3, 
                 fixed = c("Direction"), 
                 pairwise = c("Phase"))

testInteractions(m3, 
                 fixed = c("Phase", "Direction"))
```


```{r}
#Summary statistics

summarySEwithin(data = data31, 
                measurevar = "F1_Change",
                withinvars = c("Direction"), 
                idvar = "Speaker",
                na.rm = TRUE)

summarySEwithin(data = data31, 
                measurevar = "F1_Change",
                withinvars = c("Direction", "Phase"), 
                idvar = "Speaker",
                na.rm = TRUE)
```

```{r}
#Effect size

r2beta(m3, partial = TRUE, 
       method = "nsj")

```

```{r}
#Cohen's d

#Direction

temp1 <- data31[which(data31$Direction == "Upshift"), "F1_Change"]
temp2 <- data31[which(data31$Direction == "Downshift"), "F1_Change"]
temp3 <- data31[which(data31$Direction == "Unshifted"), "F1_Change"]


cohen.d(temp1, temp2)
cohen.d(temp1, temp3)
cohen.d(temp2, temp3)

#Interaction

##Hold

temp1 <- data31[which(data31$Direction == "Upshift" & data31$Phase == "Hold"),
                "F1_Change"]
temp2 <- data31[which(data31$Direction == "Downshift" & data31$Phase == "Hold"),
                "F1_Change"]
temp3 <- data31[which(data31$Direction == "Unshifted" & data31$Phase == "Hold"),
                "F1_Change"]

cohen.d(temp1, temp2)
cohen.d(temp1, temp3)
cohen.d(temp2, temp3)

##Washout

temp1 <- data31[which(data31$Direction == "Upshift" & 
                        data31$Phase == "Washout"),
                "F1_Change"]
temp2 <- data31[which(data31$Direction == "Downshift" & 
                        data31$Phase == "Washout"),
                "F1_Change"]
temp3 <- data31[which(data31$Direction == "Unshifted" & 
                        data31$Phase == "Washout"),
                "F1_Change"]

cohen.d(temp1, temp2)
cohen.d(temp1, temp3)
cohen.d(temp2, temp3)
```

#Word frequency

```{r}
#Exclude the Unshifted

data32 <- data31[which(data31$Direction != "Unshifted"), ]

#Sign-flip the Upshift

data32$F1_Sign <- ifelse(data32$Direction == "Upshift", 
                         (data32$F1_Change * -1), 
                         data32$F1_Change)

#Plot check

temp1 <- summarySEwithin(data = data32, 
                         measurevar = "F1_Sign",
                         withinvars = c("Direction", "Phase", "Word"), 
                         idvar = "Speaker",
                         na.rm = TRUE)

ggplot(data = temp1, aes(x = Phase, y = F1_Sign, 
                         color = Direction, group = Direction)) +
  geom_point() + 
  geom_line() + 
  geom_errorbar(aes(ymin = F1_Sign - se, ymax = F1_Sign + se), 
                width = 0.5,
                position = position_dodge(0)) + 
  theme_classic() + 
  ylab("F1 change (mel)") + 
  xlab("Block_10") + 
  facet_grid(. ~ Word)+ 
  geom_hline(yintercept = 0, linetype = "dashed", 
             color = "black", linewidth = 0.5) + 
  theme(legend.position = "top", 
        legend.title = element_blank(), 
        legend.text = element_text(size = 10, margin = margin(r = 30)),
        axis.title.x = element_text(vjust = -0.5),
        plot.title = element_text(size = 15),
        axis.ticks.x=element_blank()) + 
  scale_color_manual(values = c("red", "blue", "gray"))

```

```{r}
#Model 

data32$Direction <- factor(data32$Direction, levels = c("Upshift", "Downshift"))

contrasts(data32$Direction) = contr.sum(2)

contrasts(data32$Direction)

data32$Phase <- factor(data32$Phase, levels = c("Hold", "Washout"))

contrasts(data32$Phase) = contr.sum(2)

contrasts(data32$Phase)

f <- F1_Sign ~ Direction * Phase * Word + 
  (Direction * Phase * Word| Speaker)

m.order <- buildmer(f,
                    data = data32,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = data32,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
m3.a <- lmer(f,
             data = data32,
             control = lmerControl(optimizer = "bobyqa",
                                   optCtrl = list(maxfun = 2e5)),
             REML = TRUE)

car::Anova(m3.a, type = 3)

testInteractions(m3.a, 
                 fixed = NULL, 
                 pairwise = c("Word"))

testInteractions(m3.a, 
                 fixed = c("Word"), 
                 pairwise = NULL)
```

```{r}

summarySEwithin(data = data32, 
                measurevar = "F1_Sign",
                withinvars = c("Word"), 
                idvar = "Speaker",
                na.rm = TRUE)
 
```

```{r}
#Effect size

r2beta(m3.a, partial = TRUE, 
       method = "nsj")


```

```{r}
#Cohen's d

temp1 <- data32[which(data32$Word == "pedicure"), "F1_Sign"]
temp2 <- data32[which(data32$Word == "pedigree"), "F1_Sign"]

cohen.d(temp1, temp2)

```


#Test the Baseline difference

```{r}
temp1 <- data3[which(data3$Phase == "Baseline"), ]

temp1 <- temp1[which(temp1$Direction != "Unshifted"), ]

temp1 <- temp1[which(temp1$Block_10 == 2), ]


f <- meanF1_mel ~ Direction * Word + 
  (Direction * Word| Speaker)

m.order <- buildmer(f,
                    data = temp1,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = temp1 ,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
temp2 <- lmer(f,
             data = temp1,
             control = lmerControl(optimizer = "bobyqa",
                                   optCtrl = list(maxfun = 2e5)),
             REML = TRUE)

car::Anova(temp2, type = 3)
```
