---
title: "Analysis_Exp3"
output: html_document
date: "2023-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(ggpubr)

library(qdapTools)
library(Rmisc)

library(lme4)
library(lmerTest)
library(buildmer)

library(phia)

library(MuMIn)
library(r2glmm)

library(effsize)
```

#Normalization

```{r}
data3 <- read.csv("F1_Exp3_S2.csv")

data3 <- unique(data3)

#Add Block_10 info

data3$Block_10 <- ceiling(data3$Trial/40)

data3 <- data3[which(data3$Word != "carbonate"), ]

temp1 <- data.frame(table(data3$Speaker, data3$Block_10, data3$Phase))

#Obtain baseline means

temp1 <- aggregate(data3$meanF1_mel, 
                   list(data3$Direction, data3$Block_10, data3$Speaker), 
                   FUN = mean) 

colnames(temp1) <- c("Direction", "Block_10", "Speaker", "meanF1")

#Limit results to the last 10 trials of baseline 

##Where is it?

temp2 <- data.frame(table(data3$Block_10, data3$Phase))
temp2 <- temp2[which(temp2$Freq != 0 & temp2$Var2 == "Baseline"),]
var1 <- max(as.numeric(as.character(temp2$Var1)))

#Found it
temp1 <- temp1[which(temp1$Block_10 == var1), ]

temp1$Tracer <- paste(temp1$Speaker, temp1$Direction, sep = "_")

data3$Tracer <- paste(data3$Speaker, data3$Direction, sep = "_")

#Pairing data from temp1 

data3$F1_Baseline <- lookup(terms = data3$Tracer, 
                            key.match = temp1$Tracer,
                            key.reassign = temp1$meanF1)

#Calculate F1 change 

data3$F1_Change <- data3$meanF1_mel - data3$F1_Baseline
```

#Test Hold & Washout

```{r}
#Restrict to the shaded trials

head(data3)

data31 <- data3[which(data3$Block_10 %in% c(12, 13)), ]

data31$Phase <- factor(data31$Phase)

contrasts(data31$Phase) = contr.sum(2)

contrasts(data31$Phase)

data31$Direction <- factor(data31$Direction)

contrasts(data31$Direction) = contr.sum(3)

contrasts(data31$Direction)

f <- F1_Change ~ Direction * Phase + 
  (Direction * Phase | Speaker) + (Direction * Phase | Word)

m.order <- buildmer(f,
                    data = data31,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = data31,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
m3 <- lmer(f,
           data = data31,
           control = lmerControl(optimizer = "bobyqa",
                                 optCtrl = list(maxfun = 2e5)),
           REML = TRUE)

car::Anova(m3, type = 3)

#Post-hoc

testInteractions(m3, 
                 pairwise = c("Direction"))

testInteractions(m3, 
                 fixed = c("Direction"))

```

#Dot plot

```{r}
head(data3)

temp1 <- data.frame(c(1:max(data3$Trial)))
var1 <- max(data3$Trial) / length(unique(data3$Word))

temp2 <- data.frame(rep(c(1:var1), each = length(unique(data3$Word)), length.out = max(data3$Trial)))

temp1 <- cbind(temp1, temp2)

colnames(temp1) <- c("Trial", "Group1")

data3$Group1 <- lookup(terms = data3$Trial,
                       key.match = temp1$Trial,
                       key.reassign = temp1$Group1)
```

```{r}
#Plot

data3$Direction <- factor(data3$Direction, levels = c("Upshift", 
                                                      "Downshift", 
                                                      "Unshifted"))

temp2 <- summarySEwithin(data = data3, 
                         measurevar = "F1_Change",
                         withinvars = c("Direction", "Group1"), 
                         idvar = "Speaker",
                         na.rm = TRUE)

temp2$Group1 <- as.numeric(as.character(temp2$Group1))
range(temp2$Group1)

ggplot(data = temp2, aes(x = Group1, y = F1_Change, color = Direction)) +
  geom_point() + 
  theme_classic() + 
  ylab("F1 change (mel)") + 
  #geom_vline(xintercept = bar_1, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #geom_vline(xintercept = bar_2, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #geom_vline(xintercept = bar_3, linetype = "twodash", 
  #           color = "black", linewidth = 0.7) + 
  #annotate("rect", xmin = 155, xmax = 165, ymin = -55, ymax = 55,
  #         alpha = 0.2,fill = "yellow") + 
  #annotate("rect", xmin = 125, xmax = 135, ymin = -55, ymax = 55,
  #         alpha = 0.2,fill = "yellow") + 
  #annotate(geom = "text", x = var_Baseline, y = 50, 
  #         label = "Baseline",color = "black", size = rel(3.0)) +  
  #annotate(geom = "text", x = var_Ramp, y = 50, 
  #         label = "Ramp", color = "black", size = rel(3.0)) + 
  #annotate(geom = "text", x = var_Hold, y =  50, 
  #         label = "Hold", color = "black", size = rel(3.0)) + 
  #annotate(geom = "text", x = var_Washout, y =  50, 
  #         label = "Washout", color = "black", size = rel(3.0)) +
  geom_hline(yintercept = 0, linetype = "solid", 
             color = "black", linewidth = 0.8) + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(),
        axis.text = element_text(size = rel(1.0)), 
        axis.title.y = element_text(size = rel(1.0)), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank()) + 
  scale_x_continuous(expand = c(0, 0), limits = c(1, 175)) +
  #scale_y_continuous(expand = c(0, 0), limits = c(-55, 55)) +
  scale_color_manual(values = c("red", "blue", "gray")) +
  ggtitle("Expriment 3_S2")

ggsave(filename = "Exp3_Group1_S2.png",
       dpi = 600,
       units = "in",
       width = 7.5,
       height = 3)
```

#Test the Baseline difference

```{r}
temp1 <- data3[which(data3$Phase == "Baseline"), ]
temp1 <- temp1[which(temp1$Direction != "Unshifted"), ]
temp1 <- temp1[which(temp1$Block_10 == 2), ]


f <- meanF1_mel ~ Direction * Word + 
  (Direction * Word| Speaker)

m.order <- buildmer(f,
                    data = temp1,
                    buildmerControl=buildmerControl(direction='order',
                                                    args=list(control=lmerControl(optimizer='bobyqa'))))

(f <- formula(m.order@model))

m.backward <- buildmer(f,
                       data = temp1 ,
                       buildmerControl=list(direction='backward',
                                            args=list(control=lmerControl(optimizer='bobyqa'))))

summary(m.backward)

(f <- formula(m.backward@model))
```

```{r}
temp2 <- lmer(f,
             data = temp1,
             control = lmerControl(optimizer = "bobyqa",
                                   optCtrl = list(maxfun = 2e5)),
             REML = TRUE)

car::Anova(temp2, type = 3)

testInteractions(temp2, 
                 pairwise = c("Direction"),
                 fixed = c("Word"))

testInteractions(temp2, 
                 pairwise = c("Word"),
                 fixed = c("Direction"))
```
