---
title: "Analysis_Exp1"
output: html_document
date: "2023-10-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(444) #Set up random seed for reproducibility

options(scipen = 999) #Turn off scientific expressions

library(tidyverse)
library(qdapTools)
library(Rmisc)

library(sp)
library(beepr)

library(mgcv)
library(itsadug)

load("data_Exp1.RData")
```

```{r}
#Adding nonlinear pattern over trials

data1a <- data1[which(data1$Direction != "Unshifted"), ]

m1a <- bam(F1_Change ~ Direction +  
              s(Trial, bs = "tp", k = 20),  
            data = data1a, method = "ML")

summary(m1a) 
gam.check(m1a)

beep(sound = 0)
```

```{r}
#Adding nonlinear pattern over trials for each group

m1b <- bam(F1_Change ~ Direction +  
              s(Trial, bs = "tp", by = Direction, k = 20), 
            data = data1a, method = "ML")

summary(m1b) 
gam.check(m1b)

#Model comparison

compareML(m1a, m1b) #model m1b has lower AIC.

beep(sound = 0)
```

```{r}
#Add random intercept by speaker

data1a$Speaker <- factor(data1a$Speaker)

m1c <- bam(F1_Change ~ Direction +  
             s(Trial, by = Direction) + 
             s(Speaker, bs = "re"),
           data = data1a, method = "ML")

compareML(m1b, m1c) #model m1c has lower AIC.
```

```{r}
#Add random intercept by speaker per group

m1d <- bam(F1_Change ~ Direction +  
             s(Trial, by = Direction) + 
             s(Speaker, Direction, bs = "re"),
           data = data1a, method = "ML")

compareML(m1c, m1d) #model m1d has lower AIC.
```

```{r}
#Try adding by speaker smooth

m1e <- bam(F1_Change ~ Direction +  
             s(Trial, by = Direction) + 
             s(Speaker, Direction, bs = "re") +
             s(Trial, Speaker,bs = "fs",m = 1),
           data = data1a, method = "ML")

compareML(m1d, m1e) #model m1e has lower AIC.
```

```{r}
#Try using random smooth per speaker per direction

m1f <- bam(F1_Change ~ Direction +  
             s(Trial, by = Direction) + 
             s(Trial, Speaker, by = Direction, bs = "fs", m = 1),
           data = data1a, method = "ML")

compareML(m1e, m1f) #model m1f has lower AIC.
```

```{r}
#Remove autocorrelation

var_AR <- acf_resid(m1f)

TEMP1 <- c()
for(i in unique(data1a$Speaker)) {
  
  temp1 <- data1a[which(data1a$Speaker == i), ]
  
  var1 <- min(temp1$Trial)
  
  temp1$Initial <- ifelse(temp1$Trial == var1, TRUE, FALSE)
  
  TEMP1 <- rbind(TEMP1, temp1)
  
}

data1a <- TEMP1

m1f_AR <- bam(formula(m1f), 
            rho = var_AR[2], AR.start = data1a$Initial,
            data = data1a, method = "ML")

summary(m1f_AR) 
gam.check(m1f_AR)

```

#Visualize results 

```{r}
par(mfrow = c(1, 2))

two.colors = c("red", "blue")

plot_smooth(m1f_AR, view = "Trial", 
            plot_all = c("Direction"),
            #se = 0, lwd = 2,
            legend_plot_all = "topleft",
            xlab = "Trial",
            ylab = "F1 change (mel)", 
            main = "Fitted values", 
            rug = FALSE, col = two.colors)

plot_diff(m1f_AR, view = "Trial",
          xlab = "Trial",
          ylab = "F1 change (mel)", 
          main = "Downshift - Upshift", 
          comp = list(Direction = c("Downshift", "Upshift")))
```


